"""add net worth snapshots

Revision ID: f2a19aaf069f
Revises: 2fdb82d34ce2
Create Date: 2026-06-16 17:19:05.809787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a19aaf069f'
down_revision: Union[str, None] = '2fdb82d34ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('net_worth_cents', sa.Integer(), nullable=False),
    sa.Column('total_assets_cents', sa.Integer(), nullable=False),
    sa.Column('total_debt_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'year', 'month', name='uq_networth_account_year_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('net_worth_snapshots')
    # ### end Alembic commands ###
